### ISSUE TITLE
Hyperparameter proposal for Armijo line search

### ISSUE THREAD

**Issue by glebmk** [arodomanov/cmc-mipt17-opt-course#1]
https://github.com/arodomanov/cmc-mipt17-opt-course/blob/ec17bbff5d847cb637b179de6cebfba7802bd906/task1/optimization.py#L27

As far as I understand, one of the crucial hyperparameters for the Armijo line search is the factor by which we multiply alpha to move it to the next step.

`alpha_{i + 1} = alpha_{i} * factor, where factor \in (0, 1)`

Maybe, we should add it as a hyperparameter to the LineSearchTool along with `c1` and `alpha_0`?

**Comment by arodomanov** [comment]
You don't need to worry about it. Simply use `factor=0.5`. There is really no point in using anything else.
